#!/usr/bin/env python3
import os
import sys
import json

if '__main__' == __name__:
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("episodes_file", help="Path to the episodes json file.")
    parser.add_argument("--destination_dir", default=".", help="""
	Path to a folder for saving the temporary download files 
	(default='.')""")
    args = parser.parse_args()

    with open(args.episodes_file, 'r') as fs:
        episodes_json = fs.read()
    episodes = json.loads(episodes_json)

    for title, episode in episodes.items():
        if 'mkv' in episode.keys():
            continue
        for ref, track in episode['tracks'].items():
            ending = os.path.basename(track['source_path']).split('.')[1]
            file_name = track['id']+'.'+ending
            destination_path = os.path.join(args.destination_dir, file_name)
            print(track['source_path'], destination_path)
