#!/usr/bin/env python3
import os
import sys
import json

def main():
    episodes_file = sys.argv[1]
    destination_dir = '.'
    try:
        destination_dir = sys.argv[2]
    except IndexError:
        pass
    with open(episodes_file, 'r') as fs:
        episodes_json = fs.read()
    episodes = json.loads(episodes_json)
    
    for title, episode in episodes.items():
        for ref, track in episode['tracks'].items():
            ending = os.path.basename(track['source_path']).split('.')[1]
            file_name = track['id']+'.'+ending
            destination_path = os.path.join(destination_dir, file_name)
            print(track['source_path'], destination_path)

if '__main__' == __name__:
    main()

